guest_list=['Einstein','Newton','Faraday','Gauss','Faraday']
print('Dear ' +guest_list[0]+ " You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[1]+ " You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[2]+ " You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[3]+ " You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[4]+ " You are invited to dine with me at Sarova on this Saturday ")
print(guest_list[3]+ " Wont be available")
guest_list[3]="Maxwell"
print('Dear ' +guest_list[0]+ " You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[1]+ " You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[2]+ " You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[3]+ " You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[4]+ " You are invited to dine with me at Sarova on this Saturday ")
print("I found a bigger dinner table")
guest_list.insert(3,"Darwin")
guest_list.insert(4,"Hitler")
guest_list.append("Phillip")
print('Dear ' +guest_list[0]+ "You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[1]+ "You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[2]+ "You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[3]+ "You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[4]+ "You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[5]+ "You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[6]+ "You are invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[7]+ "You are invited to dine with me at Sarova on this Saturday ")
print('I can only invite two Guests')
guest_list.pop()
guest_list.pop()
guest_list.pop()
guest_list.pop()
guest_list.pop()
guest_list.pop()
print('Dear ' +guest_list[0]+ "You are still invited to dine with me at Sarova on this Saturday ")
print('Dear ' +guest_list[1]+ "You are still invited to dine with me at Sarova on this Saturday")
del guest_list[0]
del guest_list[0]
print(guest_list)
